name: Lint-test

on: 
  - push

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install
        run: make install
      - name: Running ESLint
        run: make lint
      - name: test coverage
        uses: actions/checkout@v2
        env:
          codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
